routes:
  logging: ./Logs/log
  venv: /home/controlperdidas/data_management_venv/bin/python3

q10user:
  user: mmartinez@isi.edu.pa
  password: 123
  miriam_selector: body > div.btn-group.bootstrap-select.input-group-sm.pull-right.modal-select.force-val.dropup.open > div > ul > li:nth-child(10) > a > span
  nathaly_selector: body > div.btn-group.bootstrap-select.input-group-sm.pull-right.modal-select.force-val.dropup.open > div > ul > li:nth-child(12) > a > span
  tania_selector: body > div.btn-group.bootstrap-select.input-group-sm.pull-right.modal-select.force-val.dropup.open > div > ul > li:nth-child(16) > a > span
  yalock_selector: body > div.btn-group.bootstrap-select.input-group-sm.pull-right.modal-select.force-val.dropup.open > div > ul > li:nth-child(8) > a > span
  cristian_selector: body > div.btn-group.bootstrap-select.input-group-sm.pull-right.modal-select.force-val.dropup.open > div > ul > li:nth-child(1) > a > span
google:
  spids:
    test: 1AsM_u2VAqkLjs3YhRDnq-Q88nfpv4EJS5X3apUo-bxY
    production: 1AsM_u2VAqkLjs3YhRDnq-Q88nfpv4EJS5X3apUo-bxY
    
  scopes:
    global: ['https://www.googleapis.com/auth/spreadsheets']

