routes:
  logging: ./Logs/log
  venv: /home/controlperdidas/data_management_venv/bin/python3

q10user:
  user: unusuario
  password: unacontraseña
  miriam_selector: body > div.btn-group.bootstrap-select.input-group-sm.pull-right.modal-select.force-val.open > div > ul > li:nth-child(10)
  nathaly_selector: body > div.btn-group.bootstrap-select.input-group-sm.pull-right.modal-select.force-val.open > div > ul > li:nth-child(12)
  tania_selector: body > div.btn-group.bootstrap-select.input-group-sm.pull-right.modal-select.force-val.open > div > ul > li:nth-child(16)
  yalock_selector: body > div.btn-group.bootstrap-select.input-group-sm.pull-right.modal-select.force-val.open > div > ul > li:nth-child(8)
  cristian_selector: body > div.btn-group.bootstrap-select.input-group-sm.pull-right.modal-select.force-val.open > div > ul > li:nth-child(1)
google:
  spids:
    test: 1AsM_u2VAqkLjs3YhRDnq-Q88nfpv4EJS5X3apUo-bxY
    production: 1AsM_u2VAqkLjs3YhRDnq-Q88nfpv4EJS5X3apUo-bxY
    
  scopes:
    global: ['https://www.googleapis.com/auth/spreadsheets']

